import {
  withdrawalQuoteSchema,
  withdrawalRequestSchema,
  withdrawalStatusSchema,
} from "@template/contracts";
import { actorId, otherId, now, pagination } from "./p04-network";

export const destination = {
  state: "CONFIRMED",
  serverNow: now,
  network: "TRON_NILE",
  address: "T" + "1".repeat(33),
  addressVersion: 1,
  confirmedAt: now,
} as const;
export const pendingDestination = {
  state: "PENDING",
  serverNow: now,
  network: destination.network,
  address: destination.address,
  version: 2,
  issuedAt: now,
  expiresAt: "2026-10-05T10:00:00.000Z",
  nextIssuanceAt: "2026-10-05T09:02:00.000Z",
  proofStatus: "PENDING",
  deliveryStatus: "ACKNOWLEDGED",
} as const;
export const withdrawalQuote = withdrawalQuoteSchema.parse({
  quoteId: actorId,
  quotedAt: now,
  quoteExpiresAt: "2026-10-05T09:10:00.000Z",
  serverNow: now,
  gross: "100",
  feeBps: 2100,
  fee: "21",
  net: "79",
  effectiveMembership: "FREE",
  subscriptionId: null,
  subscriptionVersion: null,
  subscriptionExpiresAt: null,
  feeBasis: "FREE_POLICY",
  policyVersion: 1,
  network: destination.network,
  recipient: destination.address,
  addressVersion: 1,
  minimumGross: "16",
  maximumGross: "500",
  eligibleNonReferral: "100",
  eligibleReferral: "0",
  fundedAllocation: { nonReferral: "100", referral: "0", total: "100" },
  requiredTopUp: "0",
  canAccept: true,
  blockReason: null,
  preview: {
    dueAt: "2026-10-08T09:00:00.000Z",
    dispatchAt: "2026-10-08T09:00:00.000Z",
    calendar: {
      zone: "Asia/Baghdad",
      countedHours: "72",
      excludedWeekdays: [6, 7],
    },
  },
});
export const withdrawal = withdrawalRequestSchema.parse({
  id: otherId,
  quoteId: actorId,
  acceptedAt: now,
  version: 1,
  scheduleVersion: 1,
  state: "SCHEDULED",
  gross: "100",
  feeBps: 2100,
  fee: "21",
  net: "79",
  effectiveMembership: "FREE",
  subscriptionId: null,
  subscriptionVersion: null,
  subscriptionExpiresAt: null,
  feeBasis: "FREE_POLICY",
  policyVersion: 1,
  network: destination.network,
  recipient: destination.address,
  addressVersion: 1,
  sourceAllocation: { nonReferral: "100", referral: "0", gross: "100" },
  calendar: withdrawalQuote.preview.calendar,
  originalDueAt: withdrawalQuote.preview.dueAt,
  dueAt: withdrawalQuote.preview.dueAt,
  dispatchAt: withdrawalQuote.preview.dispatchAt,
  serverNow: now,
  remainingCountedMilliseconds: "259200000",
  remainingCountedHours: "72",
  actions: [],
  finalizedAt: null,
  release: null,
});
export const withdrawalStatus = withdrawalStatusSchema.parse({
  serverNow: now,
  withdrawalExecutionReady: true,
  network: "TRON_NILE",
  destination,
  activeWithdrawal: null,
  withdrawalsBlocked: false,
});
export const withdrawalHistory = { items: [], pagination };
